### ISSUE TITLE
Document how to preview changes locally on M1 (and M2?) Macs

### ISSUE THREAD

**Issue by cbrownstein-lambda** [LambdaLabs/lambda-docs#237]
Following the existing instructions for [previewing changes locally](https://github.com/LambdaLabs/lambda-docs#previewing-your-changes-locally) produces `ld-linux-x86-64.so.2: /usr/lib/hugo/hugo: Not a valid dynamic program`.

Using the following `docker-compose.yaml` and `Dockerfile` doesn't solve the problem:

```yaml
version: "3.3"
​
services:
​
  site:
    image: lambdalabs/lambda-docs
    platform: linux/amd64
    build:
      context: .
    command: server
    ports:
      - "1313:1313"
    volumes:
      - .:/src
```

```dockerfile
FROM --platform=linux/amd64 klakegg/hugo:ext-alpine
​
RUN apk add git && \
  git config --global --add safe.directory /src
```

cc: @brasmi
